# Generated by Django 2.0.2 on 2018-02-04 00:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medicus', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctor',
            name='profession',
            field=models.CharField(max_length=120),
        ),
    ]
